exclude: '^docs/|/migrations/|devcontainer.json'
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files


  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort


  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
